# Generated by Django 5.2.8 on 2025-11-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paciente_laudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='laudo',
        ),
    ]
